typography_spectrum: 0.78131
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.00574055383913219
  lightness: 0.025564471259713173
  saturation: 0.03156898356974125
  rhythmicContrast: 0.6148641516920179
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49315
analytics:
  google: null
  facebook: null
  twitter: null
name: David Rodolfo Tejeda
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Nurturing a New Paradigm
purpose: []
