name: David R Tejeda
favicon: null
layout_spectrum: 0.9990011877380311
typography_spectrum: 0.6735018277540803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.00574055383913219
  lightness: 0.025564471259713173
  saturation: 0.03156898356974125
  rhythmicContrast: 0.6148641516920179
purpose: []
